---
- name: ODOO | Update DB
  shell: "{{ deploy_folder }}/current/venv/bin/click-odoo-update -c {{ odoo_conf }} -d {{ dbname }} --i18n-overwrite --if-exists"

- name: ODOO | Service stop
  become: true
  systemd:
    name: "{{ odoo_service }}"
    state: started

- name: NGINX | Creating a symlink for odoo
  become: true
  file:
    src: "/etc/nginx/sites-available/{{ nginx_odoo_conf }}"
    dest: "/etc/nginx/sites-enabled/{{ nginx_enabled_conf }}"
    state: link
    force: true

- name: NGINX | Service reload
  become: true
  systemd:
    name: nginx
    state: reloaded
